package com.devmatch.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AuditHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditHistoryAllPropertiesEquals(AuditHistory expected, AuditHistory actual) {
        assertAuditHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertAuditHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditHistoryAllUpdatablePropertiesEquals(AuditHistory expected, AuditHistory actual) {
        assertAuditHistoryUpdatableFieldsEquals(expected, actual);
        assertAuditHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditHistoryAutoGeneratedPropertiesEquals(AuditHistory expected, AuditHistory actual) {
        assertThat(actual)
            .as("Verify AuditHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditHistoryUpdatableFieldsEquals(AuditHistory expected, AuditHistory actual) {
        assertThat(actual)
            .as("Verify AuditHistory relevant properties")
            .satisfies(a -> assertThat(a.getEntityType()).as("check entityType").isEqualTo(expected.getEntityType()))
            .satisfies(a -> assertThat(a.getEntityId()).as("check entityId").isEqualTo(expected.getEntityId()))
            .satisfies(a -> assertThat(a.getFieldName()).as("check fieldName").isEqualTo(expected.getFieldName()))
            .satisfies(a -> assertThat(a.getOldValue()).as("check oldValue").isEqualTo(expected.getOldValue()))
            .satisfies(a -> assertThat(a.getNewValue()).as("check newValue").isEqualTo(expected.getNewValue()))
            .satisfies(a -> assertThat(a.getUsuario()).as("check usuario").isEqualTo(expected.getUsuario()))
            .satisfies(a -> assertThat(a.getFechaModificacion()).as("check fechaModificacion").isEqualTo(expected.getFechaModificacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditHistoryUpdatableRelationshipsEquals(AuditHistory expected, AuditHistory actual) {
        // empty method
    }
}
