package com.devmatch.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DeveloperAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeveloperAllPropertiesEquals(Developer expected, Developer actual) {
        assertDeveloperAutoGeneratedPropertiesEquals(expected, actual);
        assertDeveloperAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeveloperAllUpdatablePropertiesEquals(Developer expected, Developer actual) {
        assertDeveloperUpdatableFieldsEquals(expected, actual);
        assertDeveloperUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeveloperAutoGeneratedPropertiesEquals(Developer expected, Developer actual) {
        assertThat(actual)
            .as("Verify Developer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeveloperUpdatableFieldsEquals(Developer expected, Developer actual) {
        assertThat(actual)
            .as("Verify Developer relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getExperienceLevel()).as("check experienceLevel").isEqualTo(expected.getExperienceLevel()))
            .satisfies(a -> assertThat(a.getBio()).as("check bio").isEqualTo(expected.getBio()))
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()))
            .satisfies(a -> assertThat(a.getGithubProfile()).as("check githubProfile").isEqualTo(expected.getGithubProfile()))
            .satisfies(a -> assertThat(a.getLinkedin()).as("check linkedin").isEqualTo(expected.getLinkedin()))
            .satisfies(a -> assertThat(a.getMotivation()).as("check motivation").isEqualTo(expected.getMotivation()))
            .satisfies(a -> assertThat(a.getUsuarioCreacion()).as("check usuarioCreacion").isEqualTo(expected.getUsuarioCreacion()))
            .satisfies(a ->
                assertThat(a.getUsuarioModificacion()).as("check usuarioModificacion").isEqualTo(expected.getUsuarioModificacion())
            )
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()))
            .satisfies(a -> assertThat(a.getFechaModificacion()).as("check fechaModificacion").isEqualTo(expected.getFechaModificacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeveloperUpdatableRelationshipsEquals(Developer expected, Developer actual) {
        assertThat(actual)
            .as("Verify Developer relationships")
            .satisfies(a -> assertThat(a.getSkills()).as("check skills").isEqualTo(expected.getSkills()));
    }
}
