package com.devmatch.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExperienceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExperienceAllPropertiesEquals(Experience expected, Experience actual) {
        assertExperienceAutoGeneratedPropertiesEquals(expected, actual);
        assertExperienceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExperienceAllUpdatablePropertiesEquals(Experience expected, Experience actual) {
        assertExperienceUpdatableFieldsEquals(expected, actual);
        assertExperienceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExperienceAutoGeneratedPropertiesEquals(Experience expected, Experience actual) {
        assertThat(actual)
            .as("Verify Experience auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExperienceUpdatableFieldsEquals(Experience expected, Experience actual) {
        assertThat(actual)
            .as("Verify Experience relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExperienceUpdatableRelationshipsEquals(Experience expected, Experience actual) {
        assertThat(actual)
            .as("Verify Experience relationships")
            .satisfies(a -> assertThat(a.getDeveloper()).as("check developer").isEqualTo(expected.getDeveloper()));
    }
}
