package com.devmatch.domain;

import static com.devmatch.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MatchResultAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatchResultAllPropertiesEquals(MatchResult expected, MatchResult actual) {
        assertMatchResultAutoGeneratedPropertiesEquals(expected, actual);
        assertMatchResultAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatchResultAllUpdatablePropertiesEquals(MatchResult expected, MatchResult actual) {
        assertMatchResultUpdatableFieldsEquals(expected, actual);
        assertMatchResultUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatchResultAutoGeneratedPropertiesEquals(MatchResult expected, MatchResult actual) {
        assertThat(actual)
            .as("Verify MatchResult auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatchResultUpdatableFieldsEquals(MatchResult expected, MatchResult actual) {
        assertThat(actual)
            .as("Verify MatchResult relevant properties")
            .satisfies(a ->
                assertThat(a.getTechnicalMatch())
                    .as("check technicalMatch")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTechnicalMatch())
            )
            .satisfies(a ->
                assertThat(a.getAiTechnicalAffinity()).as("check aiTechnicalAffinity").isEqualTo(expected.getAiTechnicalAffinity())
            )
            .satisfies(a ->
                assertThat(a.getAiMotivationalAffinity()).as("check aiMotivationalAffinity").isEqualTo(expected.getAiMotivationalAffinity())
            )
            .satisfies(a ->
                assertThat(a.getAiExperienceRelevance()).as("check aiExperienceRelevance").isEqualTo(expected.getAiExperienceRelevance())
            )
            .satisfies(a -> assertThat(a.getAiComment()).as("check aiComment").isEqualTo(expected.getAiComment()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatchResultUpdatableRelationshipsEquals(MatchResult expected, MatchResult actual) {
        assertThat(actual)
            .as("Verify MatchResult relationships")
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()))
            .satisfies(a -> assertThat(a.getDeveloper()).as("check developer").isEqualTo(expected.getDeveloper()));
    }
}
